### ISSUE TITLE
Occasionally Errors

### ISSUE THREAD

**Issue by DustinBrinkFB** [KageKirin/get-unity-bundle-version#5]
[get-unity-bundle-version](https://github.com/KageKirin/get-unity-bundle-version) has been erroring on my project lately. It was working flawlessly for months, and now all of a sudden occasional errors. I'm running pretty standard configuration, and I can confirm I do see the ` bundleVersion: 0.2.23` in the ProjectSettings.asset 

It seems to detect the major, minor, patch version correctly but maybe errors out trying to find prerelease/buildmetadata info. Which I'm not even sure that that is, or why it would be needed. It's not mentioned in the documentation. 

run command
```
Run KageKirin/get-unity-bundle-version@v1.0.0
  with:
    file: Core/ProjectSettings/ProjectSettings.asset
    regex: ^(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)(\.(?<patch>0|[1-9]\d*))?(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
```

Error
```json
{
  groups: [Object: null prototype] {
    major: '0',
    minor: '2',
    patch: '23',
    prerelease: undefined,
    buildmetadata: undefined
  }
}
```
